const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
const enabled=process.env.CADMIV_TEST_JSDOM;
test('Formulário e telas no DOM do navegador',{skip:!enabled},async t=>{
 const {JSDOM}=require(enabled);const root=path.join(__dirname,'..');
 const html=fs.readFileSync(path.join(root,'cadastro.html'),'utf8');
 const dom=new JSDOM(html,{url:'http://localhost:10000/cadastro.html',runScripts:'outside-only'});const w=dom.window,d=w.document;
 let calls=[];w.fetch=async(url,opts)=>{calls.push({url,body:JSON.parse(opts.body)});return {ok:false,json:async()=>({erro:'Erro controlado para teste'})};};w.HTMLElement.prototype.scrollIntoView=()=>{};
 if(d.readyState==='loading')await new Promise(r=>d.addEventListener('DOMContentLoaded',r,{once:true}));new (require('node:vm').Script)(fs.readFileSync(path.join(root,'cadastro.js'),'utf8')).runInContext(dom.getInternalVMContext());d.dispatchEvent(new w.Event('DOMContentLoaded'));
 await t.test('Campos e dependentes pertencem ao formulário; IDs únicos',()=>{const ids=[...d.querySelectorAll('[id]')].map(e=>e.id);assert.equal(ids.length,new Set(ids).size);for(const name of ['marca','nome','cpf','email','telefone','senha','modelo','chassi','dep1_nome','dep2_nome','responsabilidade'])assert.equal(d.querySelector('[name="'+name+'"]').form.id,'form-cadastro');assert.equal(d.querySelector('[name="marca"]').required,true);});
 await t.test('Troca de plano reativa obrigatoriedade dos dependentes',()=>{d.getElementById('combo3').checked=true;w.gerenciarCombo();assert.equal(d.querySelector('[name="dep2_nome"]').disabled,false);assert.equal(d.querySelector('[name="dep2_nome"]').required,true);d.getElementById('combo1').checked=true;w.gerenciarCombo();assert.equal(d.querySelector('[name="dep2_nome"]').disabled,true);assert.equal(d.getElementById('responsabilidade').required,false);});
 await t.test('Envio inclui marca e campos certos, e mantém formulário após erro',async()=>{const fixture=require('./fixture')();for(const [key,value] of Object.entries(fixture)){const el=d.querySelector('[name="'+key+'"]');if(el && el.type!=='radio')el.value=value;}d.getElementById('nasc_dia').value='1';d.getElementById('nasc_mes').value='1';d.getElementById('cadmiv_ano').value='1990';d.getElementById('combo1').checked=true;assert.equal(d.getElementById('form-cadastro').checkValidity(),true);d.getElementById('form-cadastro').dispatchEvent(new w.Event('submit',{cancelable:true}));await new Promise(r=>setTimeout(r,30));assert.equal(calls.at(-1).url,'/api/cadastros');assert.equal(calls.at(-1).body.marca,'Marca Teste');assert.equal(calls.at(-1).body.nome,fixture.nome);assert.equal(calls.at(-1).body.nascimento,'1990-01-01');assert.equal(d.getElementById('mensagem-cadastro').textContent,'Erro controlado para teste');assert.equal(d.getElementById('btn-enviar').disabled,false);});
 await t.test('Páginas não usam sucesso simulado ou armazenamento pessoal',()=>{for(const name of ['cadastro.html','validar.html','login.html','cartao.html','botao.html','alerta.html','fiscalizacao.html']){const content=fs.readFileSync(path.join(root,name),'utf8');assert.ok(!content.includes('localStorage.setItem'));assert.ok(!content.includes('Pagamento PIX confirmado'));assert.ok(!content.includes('shadowSenha'));const page=new JSDOM(content);for(const el of page.window.document.querySelectorAll('script[src]'))assert.ok(fs.existsSync(path.join(root,el.getAttribute('src'))));page.window.close();}});
 w.close();
});
